name: cloud-db
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DATABASE_PASSWORD:-P@ssw0rd!}"
    ports:
      - "${DATABASE_PUBLIC_PORT:-1433}:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mssql-data:

networks:
  default:
    driver: bridge